env: "CartPole-v1"
device: "cpu"

training:
  total_steps: 10
  initial_episodes: 1
  train_every: 5
  train_steps: 2
  batch_size: 2
  seq_length: 5

model:
  embed_dim: 128
  rssm:
    stoch_dim: 8
    deter_dim: 16
    hidden_dim: 32
  lr: 0.0006
  kl_free_nats: 3.0

actor:
  lr: 0.00008
  horizon: 5
critic:
  lr: 0.00008
  gamma: 0.99
  lambda: 0.95

buffer:
  capacity: 1000
